export const GET_ALL_PRODUCTS = 'GET_ALL_PRODUCTS';
export const ADD_TO_CART = 'ADD_TO_CART';
export const HANDLE_INCREMENT_ITEM = 'HANDLE_INCREMENT_ITEM';
export const HANDLE_DECREMENT_ITEM = 'HANDLE_DECREMENT_ITEM';